More code

diff --git a/LUKSUS b/LUKSUS
--- a/LUKSUS
+++ b/LUKSUS
@@ -32,6 +32,8 @@ keydir=/keys
 keyfile=/keys/$name.key
 headerfile=/keys/$name.luks.header
 mountpoint=/mnt/$name
+FILE="/tmp/out.$$"
+GREP=`which grep`
 
 ###############################
 ###############################
@@ -73,10 +75,6 @@ then
 exit 1
 fi
 
-FILE="/tmp/out.$$"
-GREP=`which grep`
-
-
 # Sanity check
 # Make sure only root can run our script
 if [[ $EUID -ne 0 ]]; then
@@ -84,12 +82,17 @@ if [[ $EUID -ne 0 ]]; then
    exit 1
 fi
 echo "Great! We are root"
-echo "Proceeding with LUKSUS"
+echo "$programname is proceeding"
 
 # Check to see if specified device exists
+#if [ -b "$device" ] || echo "$device was not found. $programname is now exiting" ; fi
+if [ -b "$device" ] ; then echo "OK, $device exists"  ;else echo "$device was not found. $programname is now exiting" && exit 1; fi
 
-
-
+# A crude dependency check, could need a list and a for loop
+if [ -z `which grep` ] ;then echo "Missing grep" && exit; fi
+if [ -z `which cryptsetup` ] ;then echo "Missing cryptsetup" && exit; fi
+if [ -z `which dialog` ] ;then echo "Missing dialog" && exit; fi
+if [ -z `which shred` ] ;then echo "Missing shred" && exit; fi
 
 # OUTPUTING SCRIPT VERSION AND DATE
 dialog --title "WELCOME TO $PROGRAMNAME" \
@@ -115,7 +118,7 @@ $headerfile\n\n\n
 
 usage: \n
 ./luksus DEVICENAME nickname \n
-EXAMPLE: ./luksus /dev/sdb1 pictures2tb
+EXAMPLE: ./luksus /dev/sdb1 testresults
 \n
 \n
 If you have not specified these arguments, the script will exit
@@ -246,8 +249,7 @@ if [ $? -ne 0 ] ; then
 
 echo ################################################
 echo Thanks for using LUKSUS
-echo DETAILS AS SUBMITTED IN THE VARIABLE
-echo WHICH WILL BE USED FOR THE DRIVE ENCRYPTION
+echo Results:
 echo DRIVE: $device
 echo NAME: $name
 echo KEYFILE: $keyfile
